class Languages{

    english =   [   `In order to start, we need to know what study program you are taking. Please select your study program from this list`,
                    `Choose education`,
                    `Choose language`,
                    `Now pick the location at which this study program is taught`,
                    `<b>Correct!</b>This is the location of your study program.<br>`,
                    `Click here</a>for more information about this location.</p>`,
                    `Try again`,
                    `Go inside`,
                    `You found the location. Unfortunately, the door is still locked. Fortunately, many things are arranged online at the university. Take a look around there first and maybe you will find there the 3 shapes that make up the key together.`,
                    `Send`,
                    `Look online for shapes`,
                    `Continue`,
                    `Welcome to your online floorplan`,
                    `Maybe it’s a good idea to send an email to the Student Service Centre about the key`,
                    `This answer is incorrect. Try again.`,
                    `Schedule`,
                    `Click continue to see the schedule`,
                    `Student Service Centre`,
                    `Mail the SSC with your personal studentmail to:ssc@hr.nl`,
                    `Different study programs and information can be found by clicking continue`,
                    `Hofplein Fountain</br> This fountain in the middle of traffic square ‘Hofplein’ was presented to the city by shipping company Van Ommeren when the company existed 100 years. The fountain is nicknamed FLIPSPUIT (Flip’s fountainhead) after Philip (Flip) van Ommeren.</br>The fountain has become the place where the people of Rotterdam celebrate their big successes, like the championship of Feyenoord or a victorious game by the Dutch national soccerteam. Supporters tend to jump into the fountain to celebrate.`,
                    `Central Station</br> The current station was officially opened on March 13 2014 by king Willem-Alexander. The design of the station won multiple international awards. The locals, however, gave is a less flattering name. It made them think of the aluminium tray in which they serve their infamous fast food invention: KAPSALON (dish with shawarma, fries and cheese).`,
                    `Feyenoord Stadium</br> Not one, not two, but three professional soccer clubs represent the city of Rotterdam. Feyenoord Stadium is located on the south bank. Supporters lovingly call it the ‘KUIP’ (the tub), because that’s what is looks like from a bird’s eye view. `,
                    `Corporate Entity (sculpture)</br> This artwork used to adorn the entrance of one of the locations of the Rotterdam University of Applied Sciences (Location Museumpark), then headquarters of Unilever. When the multinational moved to a new building the sculpture, often referred to as SCHROOTHOOP (heap of scrap), moved with them.`,
                    `Erasmus Bridge</br> The inhabitants of Rotterdam invented more than 20 nicknames for their beloved iconic bridge. The ZWAAN (the swan) is the most common one.`,
                    `Blaak Station</br> The architect was asked to make sure travelers would easily find their way to entrance of the underground train and subway station. That resulted in a remarkable construction that shows some likeness with a flying saucer. Others recognize a withered sunflower or…and you need some more imagination for this one: a FLUITKETEL (tea kettle).`,
                    `Erasmus Medical Centre</br> Several smaller hospitals and clinics merged with the faculty of medicine of the Erasmus University to become the Erasmus Medical Centre. When you look at it from a distance it looks like a big, white, square tower. Some call it the refrigerator or KOELKAST.`,
                    `Binnenrotte Square</br> A market with fresh produce is held every Tuesday and Saturday. This square also hosts many events during the year. Archeological excavations on this spot have found the earliest settlements on the riverside of the Rotte, the beginning of Rotterdam. The Binnenrotte is a big open space. That gave it its nickname LANDINGSBAAN (airport runway).`,
                    `Market Hall</br> This paradise of fresh products, delicacies and food stands sees a lot of tourists, many of whom come to see one thing: the ceiling. The immense artwork gave the building its nickname SIXTIJNSE KAPEL (Sixteen Chapel) `,
                    `Central Library</br> The remarkeble yellow tubes on the outside of this building make people think more of a GASFABRIEK (gas factory) than a library. Like many other buildings in town the exterior of the building is decorated with a quote form a famous inhabitant, the humanist thinker Desiderius Erasmus: “Heel de aarde is je vaderland” (The whole world is your homeland). You can visit the Erasmus Experience to learn more about him. `,
                    `Beurstraverse</br> A shopping alley below streetlevel that crosses the Coolsingel. Nobody knows its real name. People just call it the KOOPGOOT (buying gutter)…`,
                    `Blaak Tower</br> Residential towel near Blaak Station. Do you understand why people call it the Pencil (POTLOOD)?`,
                    `Stylized Flower (Sculpture)</br> This originally nameless artwork was a gift of the Bijenkorf (Mall) to the city. It was later given the title ‘Stylized Flower’. Some locals just call it the ‘Thing’ of, more original: the traincrash (SPOORWEGONGELUK) `,
                    `My name is Cees Jansen. At a student association you'll make friends for life. Each association has their own culture. Our association is the oldest of Rotterdam and has existed for over a hundred years!`,
                    `We organise the best parties in our society. I also have a very fun club with which I study and do all kinds of things. During the introduction associations go through the entire city to promote themselves for first years. I will now head out to my own society 😉. Love, Zoë`,
                    `Hi, I am Loes. I like studying together with an association. Of course I also have joined to relax, get to know people, etc. Studying en being a member go hand in hand. Well, I'm off to "Koinoonia"`, 
                    `Hey, I am Donna. I am also a member at an association. As a student association we are also committed to social projects. And you learn a lot by organising the events and through commisions. A really good addition to my time as a student.`,
                    `NSR is the biggest christian association in Rotterdam. We are located on the Eendrachtsplein. Compared to all RKvV-associations we are the youngest. Yet we've existed since 1987! We combine friendship, insight and conviviality. Stop by to get to know us! Greetings, Werner`,
                    `Question 1: "icon of Rotterdam"`,
                    `Question 2: "Time for a party"`,
                    `Question 4: "RKVV"`,
                    `Question 3: "A round?"`,
                    `Click on the card to put a dot on the card, click on the dot to remove it. Eventually the outcome must be entered in the notebook!</br>`,
                    `Fancy a party? Sure, but…do you have the time?</br></br>Now that you're a student you will be busy studying. Do you even have time to do something fun?</br></br>Imagine: You go to bed at eleven o'clock and wake at seven to go back to school. On the weekends you usually go to bed a little later, but you're total sleep is as long as usual. You have 0:45 hours of travel time to school, and you need half an hour to get dressed and eat breakfast. You have classes from Monday to Thursday from 8:30 to 10:10 and you have another class from 12:10 to 13:50. On Friday you have the same lessons, but those are taught online through Microsoft Teams. Apart from your classes you need about 4 hours to study. You usually do this efficiently in between classes, so you have more free time at night and during the weekend. You make your own food: this takes half an hour and you finish dinner in 20 minutes. Each week you also work 14 hours in a coffee bar in town. You talk to your parents (or grandpa/grandma/aunts) on the phone for about 30 mins each week. Oh, and you spend about one and a half hour each day on social media...</br></br>How much time do you have left to relax?</br></br>On avarage ... hours a day.`,
                    `How much money do I have left for a round?`,
                    `Make an appointment here`,
                    `Counselor`,
                    `Dean`,
                    `Put the right color with the right person.`,
                    `Need help? Talk to someone about it! You need to be here: Help with study. Hogeschool Rotterdam offers all kinds of one-on-one guidance and help. But....all doors are locked. Crack the lettercode to open all doors, so you can use all our guidance!`,
                    `The puzzle is solved`,
                    `Here comes the peer coach!`,
                    `Continue`,
                    `sometimes it's not about what you can hear, but about what you can see`,
                    `Are you sure you want to use hint 1? This hint will help you with the puzzle for the 'Peercoach' door, but als gives minus points for your score. (less points is better) \n \n this pop-up will only show once. Next time you click on the envelop the hint will be used.`,
                    `Read the confirmation mail for your cellular appointment with Sara Vonk again diligently.`,
                    `Are you sure you want to use hint 2? This hint will help you with the puzzle for the 'Dean' door, but als gives minus points for your score. (less points is better) \n \n this pop-up will only show once. Next time you click on the envelop the hint will be used.`,
                    `Interviews are a numbers game sometimes.`,
                    `Are you sure you want to use hint 3? This hint will help you with the puzzle for the 'Student aan zet' door, but als gives minus points for your score. (less points is better) \n \n this pop-up will only show once. Next time you click on the envelop the hint will be used.`,
                    `<b>Incorrect!</b>This is not the location of your study program.<br>`,
                    `Congratulations`,
                    `You passed this level`,
                    `You can now take a break<br>Durig this break you will not be timed<br>Press the button to begin act `,
                    `Begin level `,
                    `Click on the door to go inside.`,
                    `Entrance`
                ]

    dutch =     [   `Om van start te gaan moeten we weten aan welke opleiding jij deel neemt. Kies uit deze lijst jouw opleiding`,
                    `Kies opleiding`,
                    `Kies taal`,
                    `Kies nu de locatie waar deze opleiding wordt gegeven`,
                    `<b>Correct!</b>Dit is de locatie van jouw opleiding.<br>`,
                    `Klik hier</a>voor meer informatie over deze locattie</p>`,
                    `Probeer opnieuw`,
                    `Loop naar binnen`,
                    `Jullie hebben de locatie gevonden. Helaas blijkt de deur nog op slot te zitten... Dat schiet natuurlijk niet op! Gelukkig zijn veel zaken op de hogeschool online geregeld. Kijk daar eerst eens rond en misschien vinden jullie daar de 3 vormen die samen de sleutel maken.`,
                    `Verzenden`,
                    `Zoek online naar vormen`,
                    `Doorgaan`,
                    `Welkom op jullie online plattegrond`,
                    `Misschien is het handig om even een mailtje te sturen naar het studenten service center over de sleutel`,
                    `Dit antwoord is onjuist. Probeer het nog een keer.`,
                    `Rooster`,
                    `Klik op doorgaan om je rooster te zien`,
                    `Student Service Center`,
                    `Mail het SSC met je persoonlijke studentenmail naar:ssc@hr.nl`,
                    `Verschillende vakken en informatie kun je vinden door op doorgaan te klikken`,
                    `De Hofpleinfontein</br> Midden in het verkeersplein Hofplein staat een grote fontein. Deze Hofpleinfontein werd in 1939 aan de stad Rotterdam geschonken door de rederij Van Ommeren die zijn honderjarige bestaan vierde. De fontein wordt in de volksmond ook wel de Flipspuit genoemd, verwijzend naar Philippus "Flip" van Ommeren. Door de centrale ligging, pal naast de Coolsingel, is het een plaats geworden waar grote successen worden gevierd van voetbalclub Feyenoord en het Nederlands voetbalelftal. Bij die overwinningen springen en feesten supporters in de fontein.`,
                    `Rotterdam Centraal Station</br> Het huidige stationsgebouw, gelegen aan het Stationsplein, werd op 13 maart 2014 officieel geopend door koning Willem-Alexander. Het ontwerp verwierf meerdere internationale prijzen. Maar Rotterdammers hebben hun stationsgebouw zoals gewoonlijk een minder flatteuze bijnaam gegeven!`,
                    `Feyenoordstadion</br> "Ga je mee naar het stadion, naar de club van Rood en Wit." Dit stadion is beter bekend onder de naam ……….`,
                    `'De Belichaamde Eenheid'</br> Dit kunstwerk stond ooit bij de ingang van een van de locaties van Hogeschool Rotterdam (Museumpark Hoogbouw); destijds het hoofdkantoor van Unilever. Bij de verhuizing naar de Weena is het kunstwerk meeverhuisd.`,
                    `Erasmusbrug</br> De Erasmusbrug is een verhaal apart en heeft wel meer dan 20 bijnamen, waaronder ‘de Zwaan’, ‘de Harp’ en 'de Wipkip’. Toch is ‘de Zwaan’ de meest gebruikte bijnaam.`,
                    `Station Blaak</br> De opdracht die de architect had bij het ontwerpen van het station was dat er voldoende oriëntatiepunten moesten zijn voor de reizigers. Dit is ook de reden dat de architect een opvallende constructie boven de grond maakte, zodat het station meteen opvalt en te herkennen is. Het ontwerp lijkt een beetje op een vliegende schotel. Veel mensen noemen het ook een verwelkte zonnebloem of fluitketel. Voor die laatste bijnaam moet je wel iets meer fantasie hebben.. `,
                    `Erasmus Medische Centrum</br> Op 1 juni 2002 fuseerden het Dijkzigtziekenhuis, het Sophia Kinderziekenhuis, de Daniel den Hoedkliniek en de "Faculteit der Geneeskunde en Gezondheidswetenschappen" van de Erasmus Universiteit Rotterdam tot het huidige Erasmus MC. “Groot, wit, vierkant…. Ik begrijp het wel” zei een Rotterdammer over de bijnaam van dit gebouw.`,
                    `Binnenrotte</br> Hier wordt op dinsdag en zaterdag markt gehouden. Daarnaast wordt het plein ook veelvuldig gebruikt voor evenementen. Opgravingen hebben aangetoond dat de vroegste nederzettingen aan de rivier de Rotte hier het begin van de stad Rotterdam hebben ingeluid. De Binnenrotte is een grote, open ruimte en daar is ook de bijnaam ‘Landingsbaan’ van afgeleid.`,
                    `Markthal</br> Deze koophemel herbergt delicatessen, verse producten, allerlei eettentjes, een supermarkt en slijterij. Toch komen de meeste toeristen voor iets anders. Camera’s klikken onafgebroken en zijn allemaal gericht op het plafond van de iconische Markthal. Rotterdammers spreken trots over hun ‘Sixtijnse Kapel’.`,
                    `Centrale Bibliotheek</br> Aan de opvallende gele buizen aan de buitenkant van dit gebouw dankt de bibliotheek haar bijnaam. Waar doet het jou aan denken? Net als meer gebouwen in Rotterdam, draagt de bibliotheek een citaat van een beroemde Rotterdammer op de gevel: “Heel de aarde is je vaderland” schreef niemand minder dan Desiderius Erasmus. Bezoek ook is de Erasmus Experience in de bibliotheek als je meer over deze grote denker wil leren.`,
                    `Beurstraverse</br> Deze verdiepte winkelstraat loopt onder de Coolsingel door. De onhandige trappen ogen misschien mooi, maar lopen voor geen meter! Grote ketens hebben hier allemaal een plek.`,
                    `De Blaaktoren Woontoren.</br> Voor Rotterdammers beter bekend als het 'potlood'.`,
                    `'De gestileerde bloem'</br> Dit naamloze kunstwerk is een geschenk van de Bijenkorf aan de stad Rotterdam. Het heeft later de titel ‘de gestileerde bloem’ gekregen. Sommige Rotterdammers noemen het gewoonweg ‘het ding’. Anderen zien er een spoorwegongeluk in.`,
                    `Mijn naam is Cees Jansen. Bij een studentenvereniging maak je vrienden voor het leven. Elke vereniging heeft een eigen cultuur. Onze vereniging is de oudste van Rotterdam en bestaat al meer dan 100 jaar!`,
                    `Bij ons op de sociëteit organiseren we de mooiste feesten. Ook heb ik een hele leuke club waarmee ik samen studeer en allerlei dingen onderneem. Tijdens de introductie gaan verenigingen trouwens de hele stad door om zichzelf te promoten onder eerstejaars. Ik ga zo maar weer eens naar mijn eigen sociëteit 😉. Liefs, Zoë `,
                    `Hi, Ik ben Loes. Ik vind het leuk om samen op de vereniging te studeren. Natuurlijk kom ik er ook om te ontspannen, mensen te leren kennen, etc. Studeren en lid zijn gaat goed samen. Nou, ik ga maar weer eens. Op naar "Koinoonia".`,
                    `Hoi, ik ben Donna. Ook ik ben lid bij een vereniging. Als studentenvereniging zetten we ons ook in voor maatschappelijke projecten. En je leert veel door commissies en het organiseren van evenementen. Echt een goede aanvulling op mijn studententijd.`,                
                    `NSR is de grootste christelijke vereniging van Rotterdam. We zitten op het Eendrachtsplein. Van alle RKvV-verenigingen zijn we de jongste. Toch bestaan we al weer sinds 1987! We combineren vriendschap, verdieping en gezelligheid. Kom eens langs om kennis te maken! Groetjes, Werner`,
                    `Vraag 1: "Rotterdamse icoon"`,
                    `Vraag 2: "Tijd voor een feestje"`,
                    `Vraag 4: "RKVV"`,
                    `Vraag 3: "Rondje?"`,
                    `Klik op de aansichtkaart om een stip te zetten, klik op de stip om deze weer weg te halen. Uiteindelijk komt er een uitkomst vul deze in in het notitieboekje!</br>`,
                    `Zin in een feestje? Maar heb ik daar wel tijd voor? Nu je student wordt zal je het razend druk gaat krijgen met je studie. Heb je eigenlijk nog wel tijd om iets leuks te doen? Je wil toch ook een beetje genieten van je studententijd? Hoe doen andere studenten dat eigenlijk?
                    </br>Stel: Je gaat om elf uur naar bed en je staat om zeven uur weer op om naar de hogeschool te gaan. In het weekend ga je vaak wat later naar bed, maar slaap je ook net zoveel uit. Je hebt 0:45 uur reistijd van huis naar school, een half uur om aan te kleden en te eten 's ochtend. Op school heb je van maandag t/m donderdag les van 8.30 uur tot 10:10 uur en je hebt les 12:10 tot 13.50 uur. Vrijdag heb je ook les, maar die volg je online via Teams. Naast je lessen heb je nog ongeveer 4 uur nodig voor je huiswerk. Dat doe je vaak efficiënt tussen de lessen door, hoef je minder 's avonds en in het weekend te doen. Je kookt je eigen eten, kost een half uurtje en tja, binnen 20 minuten heb je dat op. Per week werk je gemiddeld 14 uur in een leuk koffietentje in de stad. Je wilt het eigenlijk niet, maar aan social media ben je bijna anderhalf uur per dag kwijt. Oh ja, en je belt natuurlijk elke week een keer met je ouders (of oma/opa/tante) voor zo'n 30 min. 
                    </br></br>Hoeveel tijd hou jij over voor ontspanning?
                    </br></br>Gemiddeld ... uur per dag.`,
                    `Hoeveel geld houd ik over voor een rondje?`,
                    `Maak hier een afspraak`,
                    `Vertrouwenspersoon`,
                    `Decaan`,
                    `Zoek de juiste kleur bij de juiste persoon.`,
                    `Hulp nodig? Blijf (er) niet (mee) rondlopen! Hier moet je zijn: Hulp bij studie. De hogeschool biedt allerlei vormen van een-op-een begeleiding en ondersteuning. Maar....alle deuren zitten op slot. Kraak de lettercode om alle deuren te openen, zodat je gebruik kunt maken van al onze begeleiding!`,
                    `De puzzel is opgelost`,
                    `Daar komt de peercoach`,
                    `doorgaan`,
                    `Soms gaat het niet om wat je hoort, maar om wat je ziet`,
                    `Weet je zeker dat je hint 1 wilt gebruiken? Deze hint helpt bij de puzzel van de 'Peercoach' deur, maar telt ook extra punten op bij je score. (minder punten is beter) \n \n deze pop-up komt maar 1 keer. De volgende keer dat je op de envelop klikt wordt de hint gebruikt."`,
                    `Lees de bevestiging mail van je telefonische afspraak met Sara Vonk nog eens zorgvuldig door.`,
                    `Weet je zeker dat je hint 2 wilt gebruiken? Deze hint helpt bij de puzzel van de 'Decaan' deur, maar telt ook extra punten op bij je score. (minder punten is beter) \n \n deze pop-up komt maar 1 keer. De volgende keer dat je op de envelop klikt wordt de hint gebruikt.`,
                    `Solliciteren is soms een numbers game.`,
                    `Weet je zeker dat je hint 3 wilt gebruiken? Deze hint helpt bij de puzzel van de 'Student aan zet' deur, maar telt ook extra punten op bij je score. (minder punten is beter) \n \n deze pop-up komt maar 1 keer. De volgende keer dat je op de envelop klikt wordt de hint gebruikt.`,
                    `<b>Incorrect!</b>Dit is niet de locatie van jouw opleiding<br>`,
                    `Gefeliciteerd`,
                    `Je hebt dit level gehaald`,
                    `Je kunt nu even pauze nemen<br>Tijdens de pauze staat de tijd stil<br>Druk op de knop om te beginnen met akte `,
                    `Begin level `,
                    `Klik op de deur om naar binnen te gaan.`,
                    `Ingang`
                ]
}