class Languages{

    english =   [   `In order to start, we need to know what course you are taking. Please select your course from this list`,
                    `Choose education`,
                    `Choose language`,
                    `Now pick the location at which this course is taught`,
                    `<b>Correct!</b>This is the location of your course.<br>`,
                    `Click here</a>for more information about this location.</p>`,
                    `Try again`,
                    `Go inside`,
                    `Oh no! The door is locked and needs a special key to open. Fill in the right shapes of the key.`,
                    `Send`,
                    `Look online for shapes`,
                    `Continue`,
                    `Welcome to your online floorplan`,
                    `Maybe it would be a good idea to mail the student service centre about the key`,
                    `This awnser is incorrect. Try again.`,
                    `Schedule`,
                    `Click continue to see the schedule`,
                    `Student Service Centre`,
                    `Mail the SSC with your personal studenmail to:ssc@hr.nl`,
                    `Different courses and information can be found bij clicking continue`,
                    `De Hofpleinfontein </br>in the center of the roundabout Hofplein is a big fountain. This Hofpleinfontein was gifted to Rotterdam by the shipping company Van Ommeren who were celebrating their onehundred years of existence. The fountain is also know as the Flipspuit, after Philippus "Flip" van Ommeren. Because of the location, right next to the Coolsingel, it has become a place where great successes are celebrated by Feyenoord and the Dutch national team. At those celebrations the fans jump and party in the water near the fountain.`,
                    `Rotterdam Centraal Station </br> The current station building, situated adjecent the Stationsplein, was officially opened by king Willem-Alexander on the 13th of march 2014. The design acquired multiple international commendations. But Rotterdam citizens have nicknamed their station building a little less flattering.`,
                    `Feyenoordstadion</br> "Ga je mee naar het stadion, naar de club van Rood en Wit." This stadion is better known under the name ……….`,
                    `'De Belichaamde Eenheid'</br> this artwork was once situated near the entrance of one of the locations of Hogeschool Rotterdam (Museumpark Hoogbouw); the headquarters of Unilever a that time. The artwork moved together with them to Weena.`,
                    `Erasmusbrug</br> The Erasmusbrug is a story on itself and has over 20 nicknames, including ‘de Zwaan’, ‘de Harp’ and 'de Wipkip’. Although ‘de Zwaan’ is the most commonly used nickname.`,
                    `Station Blaak</br> The task the architect had while designing the station was that there had to be enough landmarks for the  travellers. This is also the reason the architect made a notable construction above ground, so the station would be recognized in an instance. The design is reminiscent of a flying saucer. A lot of people also call it a withered sunflower or fluitketel. The last nickname requires a bit of fantasy though..`,
                    `Erasmus Medische Centrum</br> On the 1st of june 2002 the Dijkzigtziekenhuis, the Sophia Kinderziekenhuis, de Daniel den Hoedkliniek and the "Faculteit der Geneeskunde en Gezondheidswetenschappen" of the Erasmus Universiteit Rotterdam fused into the current Erasmus MC. "Big, white, square.. I get it" said a local about the nickname for this building.`,
                    `Binnenrotte</br> On tuesdays and saturdays a market is held here. Besides that the square is also widely used for events. Excavations showed that the first civilizations settled here near the river de Rotte, this started the city Rotterdam. The Binnenrotte is a big, open space where the name "landingsbaan" comes from.`,
                    `Markthal</br> This buyers heaven accommodates delicacies, fresh produce, all kinds of diners, a supermarket and a liqour store. Although most tourists come for something else. Cameras snap pictures without pause and all of them aimed at the ceiling of the iconic Martkhal. Locals speak proudly about their 'sixtijnse kapel'.`,
                    `Centrale Bibliotheek</br> Aan de opvallende gele buizen aan de buitenkant van dit gebouw dankt de bibliotheek haar bijnaam. Waar doet het jou aan denken? Net als meer gebouwen in Rotterdam, draagt de bibliotheek een citaat van een beroemde Rotterdammer op de gevel: “Heel de aarde is je vaderland” schreef niemand minder dan Desiderius Erasmus. Bezoek ook is de Erasmus Experience in de bibliotheek als je meer over deze grote denker wil leren.`,
                    `Beurstraverse</br> Deze verdiepte winkelstraat loopt onder de Coolsingel door. De onhandige trappen ogen misschien mooi, maar lopen voor geen meter! Grote ketens hebben hier allemaal een plek.`,
                    `De Blaaktoren Woontoren.</br> Voor Rotterdammers beter bekend als het 'potlood'.`,
                    `'De gestileerde bloem'</br> Dit naamloze kunstwerk is een geschenk van de Bijenkorf aan de stad Rotterdam. Het heeft later de titel ‘de gestileerde bloem’ gekregen. Sommige Rotterdammers noemen het gewoonweg ‘het ding’. Anderen zien er een spoorwegongeluk in.`,
                    `My name is Cees Jansen. At a student association you'll make friends for life. Each association has their own culture. Our association is the oldest of Rotterdam and has existed for over a hundred years!`,
                    `We organise the best parties in our society. I also have a very fun club with which I study and do all kinds of things. During the introduction associations go through the entire city to promote themselves for first years. I will now head out to my own society 😉. Love, Zoë`,
                    `Hi, I am Loes. I like studying together with an association. Of course I also have joined to relax, get to know people, etc. Studying en being a member go hand in hand. Well, I'm off to "Koinoonia"`, 
                    `Hey, I am Donna. I am also a member at an association. As a student association we are also committed to social projects. And you learn a lot by organising the events and through commisions. A really good addition to my time as a student.`,
                    `NSR is the biggest christian association in Rotterdam. We are located on the Eendrachtsplein. Compared to all RKvV-associations we are the youngest. Yet we've existed since 1987! We combine friendship, insight and conviviality. Stop by to get to know us! Greetings, Werner`,
                    `Question 1: "icon of Rotterdam"`,
                    `Question 2: "Time for a party"`,
                    `Question 3: "RKVV"`,
                    `Question 4: "A round?"`,
                    `Click on the card to put a dot on the card, click on the dot to remove it. Eventually the outcome must be entered in the notebook!</br> Hint: It is only the first dutch word you see after you entered everything.`,
                    `Fancy a party? But do I even have time? Now that you're a student you will be busy with learning. Do you have time to do something fun? You do want to enjoy your time as a student, right? How are other students doing this?
                    </br>Imagine: You go to bed at eleven o'clock and wake at seven to go back to school. On the weekends you usually go to bed a little later, but you also sleep just as much as usual. You have 0:45 hours of traveltime from your home to school, half an hour to get dressed and eat breakfast. You have lessons on monday to thursday from 8:30 to 10:10 and you have another lesson from 12:10 to 13:50. On friday you also have the same lessons, but those are online throuhg Teams. Apart from your lessons you need about 4 hours for your homework. You usually do this efficiently between lessons, so you have less to do in the weekends and at night. You cook your own food, takes half an hour and you've eaten that in 20 minutes. Each week you work for 14 hours in a coffeebar in town. You don't want to, but you lose about one and a half hour each day to social media. Oh and you call your parents (or grandpa/grandma/aunts) for about 30 mins each week.
                    </br></br>How much time do you have left for relaxation?
                    </br></br>On avarage ... hours a day.`,
                    `How much money do I have left for a round?`,
                    `Make an appointment here`,
                    `Counselor`,
                    `Dean`,
                    `Put the right color with the right person.`,
                    `Need help? Don't let it sit! You need to be here: Help with study. Hogeschool Rotterdam offers all kinds of one-on-one guidance and help. But....all doors are locked. Crack the lettercode to open all doors, so you can use all our guidance!`,
                    `The puzzle is solved`,
                    `There is the peercoach`,
                    `Continue`,
                    `sometimes it's not about what you can hear, but about what you can see`,
                    `Are you sure you want to use hint 1? This hint will help you with the puzzle for the 'Peercoach' door, but als gives minus points for your score. (less points is better) \n \n this pop-up will only show once. Next time you click on the envelop the hint will be used.`,
                    `Read the confirmation mail for your cellular appointment with Sara Vonk again diligently.`,
                    `Are you sure you want to use hint 2? This hint will help you with the puzzle for the 'Dean' door, but als gives minus points for your score. (less points is better) \n \n this pop-up will only show once. Next time you click on the envelop the hint will be used.`,
                    `Interviews are a numbers game sometimes.`,
                    `Are you sure you want to use hint 3? This hint will help you with the puzzle for the 'Student aan zet' door, but als gives minus points for your score. (less points is better) \n \n this pop-up will only show once. Next time you click on the envelop the hint will be used.`,
                    `<b>Incorrect!</b>This is not the location of your course.<br>`,
                    `Congratulations`,
                    `You passed this act`,
                    `You can now take a break<br>Durig this break you will not be timed<br>Press the button to begin act `,
                    `Begin act `
                ]

    dutch =     [   `Om van start te gaan moeten we weten aan welke opleiding jij deel neemt. Kies uit deze lijst jouw opleiding`,
                    `Kies opleiding`,
                    `Kies taal`,
                    `Kies nu de locatie waar deze opleiding wordt gegeven`,
                    `<b>Correct!</b>Dit is de locatie van jouw opleiding.<br>`,
                    `Klik hier</a>voor meer informatie over deze locattie</p>`,
                    `Probeer opnieuw`,
                    `Loop naar binnen`,
                    `Oh nee! De deur zit dicht en heeft een specifieke sleutel nodig om gepend te worden. Vul de juisten vormen van de sleutel in.`,
                    `Verzenden`,
                    `Zoek online naar vormen`,
                    `Doorgaan`,
                    `Welkom op jullie online plattegrond`,
                    `Misschien is het handig om even een mailtje te sturen naar het studenten service center over de sleutel`,
                    `Dit antwoord is onjuist. Probeer het nog een keer.`,
                    `Rooster`,
                    `Klik op doorgaan om je rooster te zien`,
                    `Student Service Center`,
                    `Mail het SSC met je persoonlijke studentenmail naar:ssc@hr.nl`,
                    `Verschillende vakken en informatie kun je vinden door op doorgaan te klikken`,
                    `De Hofpleinfontein</br> Midden in het verkeersplein Hofplein staat een grote fontein. Deze Hofpleinfontein werd in 1939 aan de stad Rotterdam geschonken door de rederij Van Ommeren die zijn honderjarige bestaan vierde. De fontein wordt in de volksmond ook wel de Flipspuit genoemd, verwijzend naar Philippus "Flip" van Ommeren. Door de centrale ligging, pal naast de Coolsingel, is het een plaats geworden waar grote successen worden gevierd van voetbalclub Feyenoord en het Nederlands voetbalelftal. Bij die overwinningen springen en feesten supporters in de fontein.`,
                    `Rotterdam Centraal Station</br> Het huidige stationsgebouw, gelegen aan het Stationsplein, werd op 13 maart 2014 officieel geopend door koning Willem-Alexander. Het ontwerp verwierf meerdere internationale prijzen. Maar Rotterdammers hebben hun stationsgebouw zoals gewoonlijk een minder flatteuze bijnaam gegeven!`,
                    `Feyenoordstadion</br> "Ga je mee naar het stadion, naar de club van Rood en Wit." Dit stadion is beter bekend onder de naam ……….`,
                    `'De Belichaamde Eenheid'</br> Dit kunstwerk stond ooit bij de ingang van een van de locaties van Hogeschool Rotterdam (Museumpark Hoogbouw); destijds het hoofdkantoor van Unilever. Bij de verhuizing naar de Weena is het kunstwerk meeverhuisd.`,
                    `Erasmusbrug</br> De Erasmusbrug is een verhaal apart en heeft wel meer dan 20 bijnamen, waaronder ‘de Zwaan’, ‘de Harp’ en 'de Wipkip’. Toch is ‘de Zwaan’ de meest gebruikte bijnaam.`,
                    `Station Blaak</br> De opdracht die de architect had bij het ontwerpen van het station was dat er voldoende oriëntatiepunten moesten zijn voor de reizigers. Dit is ook de reden dat de architect een opvallende constructie boven de grond maakte, zodat het station meteen opvalt en te herkennen is. Het ontwerp lijkt een beetje op een vliegende schotel. Veel mensen noemen het ook een verwelkte zonnebloem of fluitketel. Voor die laatste bijnaam moet je wel iets meer fantasie hebben.. `,
                    `Erasmus Medische Centrum</br> Op 1 juni 2002 fuseerden het Dijkzigtziekenhuis, het Sophia Kinderziekenhuis, de Daniel den Hoedkliniek en de "Faculteit der Geneeskunde en Gezondheidswetenschappen" van de Erasmus Universiteit Rotterdam tot het huidige Erasmus MC. “Groot, wit, vierkant…. Ik begrijp het wel” zei een Rotterdammer over de bijnaam van dit gebouw.`,
                    `Binnenrotte</br> On tuesdays and saturdays a market is held here. Besides that the square is also widely used for events. Excavations showed that the first civilizations settled here near the river de Rotte, this started the city Rotterdam. The Binnenrotte is a big, open space where the name "landingsbaan" comes from.`,
                    `Markthal</br> Deze koophemel herbergt delicatessen, verse producten, allerlei eettentjes, een supermarkt en slijterij. Toch komen de meeste toeristen voor iets anders. Camera’s klikken onafgebroken en zijn allemaal gericht op het plafond van de iconische Markthal. Rotterdammers spreken trots over hun ‘Sixtijnse Kapel’.`,
                    `Centrale Bibliotheek</br> The yellow tubes on the outside of this building made the library's nickname. What does it make you think of? Just like other buildings in Rotterdam, it carries a quote said by a famous Rotterdammer on its facade: “Heel de aarde is je vaderland” wrote noone less than Desiderius Erasmus. Visit the Erasmus Experience in the library if you want to learn more about this great thinker.`,
                    `Beurstraverse</br> This deepened shopping discrict runs under the Coolsingel. The awkward staircase might look pretty, but they aren't very easy to traverse. Big brands all have a place here.`,
                    `De Blaaktoren Woontoren.</br> Better known under the locals as the 'potlood'`,
                    `'De gestileerde bloem'</br> This nameless artwork is a gift to the city of Rotterdam by the Bijenkorf. It has received the title 'de gestileerde bloem' later on. Some locals just plainly call it 'het ding'. Others see a 'spoorwegongeluk'.`,
                    `Mijn naam is Cees Jansen. Bij een studentenvereniging maak je vrienden voor het leven. Elke vereniging heeft een eigen cultuur. Onze vereniging is de oudste van Rotterdam en bestaat al meer dan 100 jaar!`,
                    `Bij ons op de sociëteit organiseren we de mooiste feesten. Ook heb ik een hele leuke club waarmee ik samen studeer en allerlei dingen onderneem. Tijdens de introductie gaan verenigingen trouwens de hele stad door om zichzelf te promoten onder eerstejaars. Ik ga zo maar weer eens naar mijn eigen sociëteit 😉. Liefs, Zoë `,
                    `Hi, Ik ben Loes. Ik vind het leuk om samen op de vereniging te studeren. Natuurlijk kom ik er ook om te ontspannen, mensen te leren kennen, etc. Studeren en lid zijn gaat goed samen. Nou, ik ga maar weer eens. Op naar "Koinoonia".`,
                    `Hoi, ik ben Donna. Ook ik ben lid bij een vereniging. Als studentenvereniging zetten we ons ook in voor maatschappelijke projecten. En je leert veel door commissies en het organiseren van evenementen. Echt een goede aanvulling op mijn studententijd.`,                
                    `NSR is de grootste christelijke vereniging van Rotterdam. We zitten op het Eendrachtsplein. Van alle RKvV-verenigingen zijn we de jongste. Toch bestaan we al weer sinds 1987! We combineren vriendschap, verdieping en gezelligheid. Kom eens langs om kennis te maken! Groetjes, Werner`,
                    `Vraag 1: "Rotterdamse icoon"`,
                    `Vraag 2: "Tijd voor een feestje"`,
                    `Vraag 3: "RKVV"`,
                    `Vraag 4: "Rondje?"`,
                    `Klik op de aansichtkaart om een stip te zetten, klik op de stip om deze weer weg te halen. Uiteindelijk komt er een uitkomst vul deze in in het notitieboekje!</br> Hint: het is alleen het eerste woord wat je krijgt nadat je alles in hebt gevuld.`,
                    `Zin in een feestje? Maar heb ik daar wel tijd voor? Nu je student wordt zal je het razend druk gaat krijgen met je studie. Heb je eigenlijk nog wel tijd om iets leuks te doen? Je wil toch ook een beetje genieten van je studententijd? Hoe doen andere studenten dat eigenlijk?
                    </br>Stel: Je gaat om elf uur naar bed en je staat om zeven uur weer op om naar de hogeschool te gaan. In het weekend ga je vaak wat later naar bed, maar slaap je ook net zoveel uit. Je hebt 0:45 uur reistijd van huis naar school, een half uur om aan te kleden en te eten 's ochtend. Op school heb je van maandag t/m donderdag les van 8.30 uur tot 10:10 uur en je hebt les 12:10 tot 13.50 uur. Vrijdag heb je ook les, maar die volg je online via Teams. Naast je lessen heb je nog ongeveer 4 uur nodig voor je huiswerk. Dat doe je vaak efficiënt tussen de lessen door, hoef je minder 's avonds en in het weekend te doen. Je kookt je eigen eten, kost een half uurtje en tja, binnen 20 minuten heb je dat op. Per week werk je gemiddeld 14 uur in een leuk koffietentje in de stad. Je wilt het eigenlijk niet, maar aan social media ben je bijna anderhalf uur per dag kwijt. Oh ja, en je belt natuurlijk elke week een keer met je ouders (of oma/opa/tante) voor zo'n 30 min. 
                    </br></br>Hoeveel tijd hou jij over voor ontspanning?
                    </br></br>Gemiddeld ... uur per dag.`,
                    `Hoeveel geld houd ik over voor een rondje?`,
                    `Maak hier een afspraak`,
                    `Vertrouwenspersoon`,
                    `Decaan`,
                    `Zoek de juiste kleur bij de juiste persoon.`,
                    `Hulp nodig? Blijf (er) niet (mee) rondlopen! Hier moet je zijn: Hulp bij studie. De hogeschool biedt allerlei vormen van een-op-een begeleiding en ondersteuning. Maar....alle deuren zitten op slot. Kraak de lettercode om alle deuren te openen, zodat je gebruik kunt maken van al onze begeleiding!`,
                    `De puzzel is opgelost`,
                    `Daar komt de peercoach`,
                    `doorgaan`,
                    `Soms gaat het niet om wat je hoort, maar om wat je ziet`,
                    `Weet je zeker dat je hint 1 wilt gebruiken? Deze hint helpt bij de puzzel van de 'Peercoach' deur, maar telt ook extra punten op bij je score. (minder punten is beter) \n \n deze pop-up komt maar 1 keer. De volgende keer dat je op de envelop klikt wordt de hint gebruikt."`,
                    `Lees de bevestiging mail van je telefonische afspraak met Sara Vonk nog eens zorgvuldig door.`,
                    `Weet je zeker dat je hint 2 wilt gebruiken? Deze hint helpt bij de puzzel van de 'Decaan' deur, maar telt ook extra punten op bij je score. (minder punten is beter) \n \n deze pop-up komt maar 1 keer. De volgende keer dat je op de envelop klikt wordt de hint gebruikt.`,
                    `Solliciteren is soms een numbers game.`,
                    `Weet je zeker dat je hint 3 wilt gebruiken? Deze hint helpt bij de puzzel van de 'Student aan zet' deur, maar telt ook extra punten op bij je score. (minder punten is beter) \n \n deze pop-up komt maar 1 keer. De volgende keer dat je op de envelop klikt wordt de hint gebruikt.`,
                    `<b>Incorrect!</b>Dit is niet de locatie van jouw opleiding<br>`,
                    `Gefeliciteerd`,
                    `Je hebt deze akte gehaald`,
                    `Je kunt nu even pauze nemen<br>Tijdens de pauze staat de tijd stil<br>Druk op de knop om te beginnen met akte `,
                    `Begin akte `
                ]
}